"""Regenerate lessons/INDEX.md and knowledge/INDEX.md (tag -> entries). Never edit the indexes by hand.
Run from the root of the working branch or of a store repository."""
import json, pathlib, re, sys

def front(path):
    text = path.read_text(encoding="utf-8")
    head = text.split("---", 2)[1]
    f = dict(re.findall(r"^(\w+):[ \t]*(.*)$", head, re.M))
    return f

def unq(v):
    v = v.strip()
    return json.loads(v) if v.startswith('"') else v

def build(kind, glob, label):
    root = pathlib.Path(kind)
    if not root.is_dir():
        return None
    by_tag, count = {}, 0
    for p in sorted(root.glob(glob)):
        f = front(p)
        eid = f["id"].split("#")[0].strip()
        tags = re.findall(r"[\w-]+:[\w.-]+", f.get("tags", ""))
        text = unq(f["title"]) if "title" in f else unq(f["statement"])
        text = text if len(text) <= 160 else text[:157].rstrip() + "..."
        extra = f" ({f['severity'].strip()})" if "severity" in f else ""
        line = f"- [{eid}]({p.as_posix()}) {text}{extra}"
        for t in tags:
            by_tag.setdefault(t, []).append(line)
        count += 1
    out = [f"# {label} index", "", "Generated by scripts/build_index.py; do not edit by hand.", f"Entries: {count}", ""]
    for t in sorted(by_tag):
        out += [f"## {t}", ""] + sorted(by_tag[t]) + [""]
    (root / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
    return count

for kind, glob, label in (("lessons", "**/L-*.md", "Lessons"), ("knowledge", "**/K-*.md", "Knowledge")):
    n = build(kind, glob, label)
    if n is not None:
        print(f"{kind}/INDEX.md: {n} entries")
